apiVersion: v2
name: synergy-wholesale-exporter
description: Prometheus exporter for Synergy Wholesale domains
type: application
home: https://github.com/yungwood/synergy-wholesale-exporter
sources:
  - https://github.com/yungwood/synergy-wholesale-exporter
keywords:
  - prometheus
  - exporter
  - domains
  - synergy-wholesale
# Release publishing overwrites version and appVersion for tagged builds.
version: 0.0.0
appVersion: "main"
maintainers:
  - name: yungwood
    url: https://github.com/yungwood
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/yungwood/synergy-wholesale-exporter
    - name: Helm repository
      url: https://yungwood.github.io/helm-charts/
