---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synergy-wholesale-exporter.fullname" . }}
  labels:
    {{- include "synergy-wholesale-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default "3" }}
  selector:
    matchLabels:
      {{- include "synergy-wholesale-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synergy-wholesale-exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "synergy-wholesale-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: {{ .Values.args }}
          {{- with .Values.command }}
          command: 
            {{- toYaml . | nindent 12  }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SYNERGY_WHOLESALE_RESELLER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "synergy-wholesale-exporter.secretName" . }}
                  key: {{ .Values.secret.resellerIDKey }}
            - name: SYNERGY_WHOLESALE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "synergy-wholesale-exporter.secretName" . }}
                  key: {{ .Values.secret.apiKeyKey }}
            - name: SYNERGY_WHOLESALE_EXPORTER_ADDRESS
              value: {{ .Values.config.address | quote }}
            - name: SYNERGY_WHOLESALE_EXPORTER_CACHE_TTL
              value: {{ .Values.config.cacheTTL | quote }}
            - name: SYNERGY_WHOLESALE_EXPORTER_API_ERROR_BACKOFF_MIN
              value: {{ .Values.config.apiErrorBackoffMin | quote }}
            - name: SYNERGY_WHOLESALE_EXPORTER_API_ERROR_BACKOFF_MAX
              value: {{ .Values.config.apiErrorBackoffMax | quote }}
            - name: SYNERGY_WHOLESALE_EXPORTER_DEBUG
              value: {{ .Values.config.debug | quote }}
            - name: SYNERGY_WHOLESALE_EXPORTER_JSON
              value: {{ .Values.config.json | quote }}
            - name: SYNERGY_WHOLESALE_EXPORTER_GOLANG_METRICS
              value: {{ .Values.config.golangMetrics | quote }}
            - name: SYNERGY_WHOLESALE_EXPORTER_DNSSEC_METRICS
              value: {{ .Values.config.dnssecMetrics | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
