{{- if .Values.secret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synergy-wholesale-exporter.secretName" . }}
  labels:
    {{- include "synergy-wholesale-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.resellerIDKey }}: {{ required "secret.resellerID is required when secret.create is true" .Values.secret.resellerID | quote }}
  {{ .Values.secret.apiKeyKey }}: {{ required "secret.apiKey is required when secret.create is true" .Values.secret.apiKey | quote }}
{{- end }}
