name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "docker-compose.yaml"
      - LICENSE
      - README.md
      - renovate.json
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "docker-compose.yaml"
      - LICENSE
      - README.md
      - renovate.json

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Determine AppVersion
        if: github.event_name != 'pull_request'
        id: vars
        run: |
          # Get the short SHA
          short_sha=${GITHUB_SHA::7}

          # Determine the version
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            version=${GITHUB_REF#refs/tags/}
          else
            version=${short_sha}
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Docker meta
        if: github.event_name != 'pull_request'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yungwood/synergy-wholesale-exporter
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
